### ISSUE TITLE
Issues running example in readme

### ISSUE THREAD

**Issue by gavin-s-smith** [StephanSeifert/SurrogateMinimalDepth#12]
There seems to be an issue with the current code. I've had it working before, but on new installs I get the following error for the example code when computing the MD:
```
RuntimeError: Error in if (is.na(depth.tree[node["splitvariable"]])) { : 
  argument is of length zero
```
When calculating the SMD the error is a segfault.

These errors can be seen in a clean Google Collaboratory instance here:
https://colab.research.google.com/drive/1PbERDHmwDtTQstsbLcgPPT_NgcmGPz-_
The instance is running: R version 3.6.3

**Comment by StephanSeifert** [comment]
Sorry for the late response. 
This problem occured because of the new version of ranger and changes that were done on the way the trees are saved. I adapted SMD (already in April) and the problem should be fixed.
